//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int ID { get; set; }
        public string currencyID { get; set; }
        public string currencyDetail { get; set; }
        public Nullable<decimal> exchangeRate { get; set; }
        public string isActive { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    }
}
